name: Node CI

on:
  pull_request:
    branches:
      - master

jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - name: Awesome readme to data
        uses: Scrum/awesome-readme-to-data-action@0.0.0
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, and run test
      run: |
        npm i
        npm run lint
