name: Node CI

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Awesome readme to data
        uses: Scrum/awesome-readme-to-data-action@v0.0.10
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "feat: update data file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, and run test
      run: |
        npm i
        npm run lint
