name: Node CI

on:
  pull_request:
    branches:
      - master

jobs:
  data:
    name: awesome readme to data
    runs-on: ubuntu-latest
    steps:
      - uses: Scrum/awesome-readme-to-data-action@v0.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, and run test
      run: |
        npm i
        npm run lint
